[package]
name = "rust_sha3"
version = "0.1.0"
edition = "2018"

[dependencies]
tiny-keccak = { version = "2.0.2", features = ["sha3"] }
hex = "0.4.2"

[profile.release]
opt-level = 3  # Corrected to a numeric value (0, 