[package]
name = "enc"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.11"
anyhow = "1.0.86"
zeroize = "1.8.1"
winapi = { version = "0.3", features = ["fileapi", "winnt"] }
